# Generated by Django 5.0.4 on 2024-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сессия платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
