# Generated by Django 5.0.4 on 2024-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_session_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
