# Generated by Django 5.0.4 on 2024-05-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_product_id_lesson_product_id'),
        ('payment', '0003_alter_payment_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_lesson',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок'),
        ),
    ]
