# Generated by Django 5.0.4 on 2024-04-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=200, verbose_name='Название курса')),
                ('image_course', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Превью курса')),
                ('description_course', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=200, verbose_name='Название урока')),
                ('image_lesson', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Превью урока')),
                ('description_lesson', models.TextField(blank=True, null=True, verbose_name='Описание урока')),
                ('url_lesson', models.URLField(blank=True, null=True, verbose_name='Ссылка на урок')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
