# Generated by Django 5.0.4 on 2024-05-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_course_url_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID урока'),
        ),
    ]
